### ISSUE TITLE
Getting Error when trying to load test data on server

### ISSUE THREAD

**Issue by trevor-wu** [e-mission/e-mission-server#601] opened 2018-09-25 00:27 UTC
<img width="562" alt="notloading" src="https://user-images.githubusercontent.com/35517530/45986202-ea76b480-c01e-11e8-99ea-6aa843308dd8.png">

There is a traceback error when running 
`$ ./e-mission-py.bash bin/debug/load_timeline_for_day_and_user.py emission/tests/data/real_examples/shankari_2015-07-22 test_july_22`

**Comment by sam11b** [comment] 2018-09-28 22:12
still an issue but only when being run on the server. works fine on trevor's local machine.

**Comment by shankari** [comment] 2018-09-29 14:32
This is a regression caused by https://github.com/e-mission/e-mission-server/commit/c26ebf6ed6c8c54ce3dbdc715d03ae869e066e53

I looked through the Testing done and I tested only the multi user scripts, not the single user.
I did test the single user pipeline as part of the related https://github.com/e-mission/e-mission-server/commit/4aa521caa2bab3c4a3802b210c6a0fa5f7e25d68, but didn't re-test when I switched to the default implementation.

ETA for fix is Sunday morning

**Comment by shankari** [comment] 2018-10-09 05:44
Should be fixed by #602. Please re-open if not :)

**Closed by shankari** 2018-10-09 05:44 UTC
